import discord
from discord.ext import commands, tasks # Import tasks
import google.generativeai as genai
import asyncio
import re
import os
from dotenv import load_dotenv
import datetime # Import datetime for inactivity check
from collections import defaultdict # For tracking channel activity

# --- Load Environment Variables ---
load_dotenv()
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not DISCORD_TOKEN or not GEMINI_API_KEY:
    print("ERROR: Discord Token or Gemini API Key not found in .env file.")
    exit()

# --- Configure Gemini ---
genai.configure(api_key=GEMINI_API_KEY)
GEMINI_MODEL_NAME = "gemini-1.5-flash"

try:
    gemini_model = genai.GenerativeModel(model_name=GEMINI_MODEL_NAME)
    print(f"Gemini model '{GEMINI_MODEL_NAME}' initialized.")
except Exception as e:
    print(f"ERROR: Failed to initialize Gemini model: {e}")
    exit()

# --- Bot Settings ---
# !! ENABLE PRIVILEGED INTENTS IN DISCORD DEV PORTAL !!
intents = discord.Intents.default()
intents.messages = True
intents.message_content = True # Privileged
intents.guilds = True
intents.presences = True      # <<<--- ADDED: PRIVILEGED INTENT
intents.members = True        # <<<--- ADDED: PRIVILEGED INTENT

bot = commands.Bot(command_prefix="~$", intents=intents, help_command=None) # Disable default help if making custom later

# --- Buffers & Activity Tracking ---
message_buffer = [] # Still global for simplicity, consider per-channel dict if scaling
MAX_BUFFER_SIZE = 5
# Dictionary to store the timestamp of the last message in each channel
# { channel_id: last_message_timestamp }
last_message_timestamps = {}
INACTIVITY_THRESHOLD = datetime.timedelta(hours=1) # Time before triggering starter
CONVERSATION_STARTER_COOLDOWN = datetime.timedelta(hours=1) # Prevent spamming starters
# Track when the last starter was sent per channel to enforce cooldown
last_starter_sent = {}

# --- Command Parsing Function ---
# (Keep find_ai_commands as it was in the previous version)
def find_ai_commands(text):
    """
    Finds all command strings matching the pattern !command(...) in the text.
    Returns a list of full command strings found (e.g., ['!say(123,"Hello")']).
    Prioritizes specifically parsed !say commands.
    """
    # Use the stricter regex for reliable parsing here
    say_commands = re.findall(r"(!say\(\s*\d+\s*,\s*(['\"]).*?\2\s*\))", text, re.DOTALL)
    # This finds tuples like ('!say(123, "Hello (world)!")', '"')
    full_say_commands = [cmd[0] for cmd in say_commands]

    if full_say_commands:
        print(f"Found potential commands (refined !say): {full_say_commands}")
        return full_say_commands
    else:
        # Fallback to generic pattern if specific !say isn't found (might be less reliable)
        pattern = r"\!([a-zA-Z_]+)\((.*?)\)"
        matches = re.findall(pattern, text, re.DOTALL)
        full_commands = [f"!{name}({args})" for name, args in matches]
        if full_commands:
             print(f"Found potential commands (generic): {full_commands}")
             return full_commands
        else:
            print("No commands found.")
            return []


# --- Command Execution Function ---
# Modified to accept an optional feedback_channel instead of ctx for tasks
async def execute_ai_command(command_string, feedback_channel=None, executing_guild=None):
    """
    Parses and executes a command string generated by the AI.

    Args:
        command_string: The full command string (e.g., '!say(12345, "Hello")').
        feedback_channel: (Optional) The discord.TextChannel to send feedback/errors to.
                          If None, errors are just printed.
        executing_guild: (Optional) The guild context, useful for permission checks if feedback_channel is None.
    """
    print(f"Attempting to execute command: {command_string}")
    say_match = re.match(r"!say\(\s*(\d+)\s*,\s*(['\"])(.*?)\2\s*\)", command_string, re.DOTALL)

    async def send_feedback(message):
        """Helper to send feedback if channel is available."""
        print(f"Feedback: {message}") # Always print
        if feedback_channel and isinstance(feedback_channel, discord.TextChannel):
            try:
                # Check permissions before sending feedback too
                guild_for_feedback = feedback_channel.guild
                if guild_for_feedback and guild_for_feedback.me:
                     perms = feedback_channel.permissions_for(guild_for_feedback.me)
                     if perms.send_messages:
                         await feedback_channel.send(f"AI Task Feedback: {message}")
                     else:
                          print(f"Cannot send feedback to {feedback_channel.id}, missing send perms.")
                elif not guild_for_feedback: # DM channel maybe? Unlikely for feedback here.
                    await feedback_channel.send(f"AI Task Feedback: {message}")

            except discord.Forbidden:
                 print(f"Cannot send feedback to {feedback_channel.id}, FORBIDDEN.")
            except discord.HTTPException as e:
                 print(f"Cannot send feedback to {feedback_channel.id}, HTTPException: {e}")


    if say_match:
        try:
            channel_id = int(say_match.group(1))
            message_content = say_match.group(3)

            print(f"Parsed !say: Channel ID={channel_id}, Message='{message_content}'")

            target_channel = bot.get_channel(channel_id)
            if not target_channel:
                 try:
                     target_channel = await bot.fetch_channel(channel_id)
                 except (discord.NotFound, discord.Forbidden):
                     await send_feedback(f"Tried `!say`, but channel {channel_id} not found or inaccessible.")
                     return
                 except discord.HTTPException as e:
                     await send_feedback(f"Tried `!say`, but Discord error during lookup for channel {channel_id}: {e}")
                     return

            if isinstance(target_channel, discord.TextChannel):
                # Determine the guild for permission check
                guild = target_channel.guild
                if not guild: # Should not happen for TextChannel but safety check
                     await send_feedback(f"Tried `!say` in channel {channel_id}, but couldn't determine its guild.")
                     return

                # Check bot permissions in that channel
                if guild.me: # Check if bot is still in the guild
                    perms = target_channel.permissions_for(guild.me)
                    if perms.send_messages:
                        # Handle potential message length limits
                        if len(message_content) > 2000:
                            print("Warning: AI message exceeds 2000 chars, sending truncated.")
                            await target_channel.send(message_content[:1997] + "...")
                        else:
                            await target_channel.send(message_content)
                        print(f"Successfully executed !say in channel {channel_id}")
                        # Avoid feedback for successful task-based say commands to reduce noise
                        # if feedback_channel: await send_feedback(f"Executed `!say` in channel {channel_id}.")
                    else:
                        await send_feedback(f"Tried `!say` in channel {channel_id}, but missing 'Send Messages' permission.")
                else:
                    await send_feedback(f"Tried `!say` in channel {channel_id}, but I'm no longer in that guild.")
            else:
                 await send_feedback(f"Tried `!say`, but channel {channel_id} is not a text channel.")

        except ValueError:
            await send_feedback(f"Tried `!say`, but channel ID invalid in `{command_string}`.")
        except discord.Forbidden:
             await send_feedback(f"Tried `!say` in channel {channel_id}, but Discord blocked me (Forbidden).")
        except discord.HTTPException as e:
             await send_feedback(f"Tried `!say` in channel {channel_id}, but Discord returned an error: {e}")
        except Exception as e:
            await send_feedback(f"Unexpected error executing `!say` command '{command_string}': {e}")
            # Log the full error for debugging
            import traceback
            print(f"Full Traceback for !say error:\n{traceback.format_exc()}")

    else:
        print(f"Command '{command_string}' not recognized or malformed.")
        # await send_feedback(f"Generated command I don't understand: `{command_string}`")


# --- Bot Events ---
@bot.event
async def on_ready():
    print("-" * 20)
    print(f"Bot is ready. Logged in as {bot.user}")
    print(f"Bot ID: {bot.user.id}")
    # Ensure member cache is populated (needed with members intent)
    print("Fetching members for all guilds...")
    for guild in bot.guilds:
        if guild.large:
             # await guild.chunk() # Use fetch_members for newer d.py
             async for member in guild.fetch_members(limit=None): pass # Iterate to ensure cache fill
        print(f"- {guild.name} ({guild.id}) - Members: {guild.member_count}")
    print("Member fetching complete.")
    print("Starting background tasks...")
    check_channel_activity.start() # Start the inactivity checker task
    print(f"Intents: {bot.intents}")
    print("-" * 20)


@bot.event
async def on_message(message):
    if message.author == bot.user:
        return # Ignore self

    # Update last message timestamp for the channel
    now = discord.utils.utcnow()
    last_message_timestamps[message.channel.id] = now

    # --- Buffer Logic ---
    if isinstance(message.channel, discord.TextChannel): # Only buffer guild messages for now
        user_data = {
            "role": "user",
            "parts": [f"User '{message.author.name}' (ID: {message.author.id}) in Channel '{message.channel.name}' (ID: {message.channel.id}) said: {message.content}"]
        }
        message_buffer.append(user_data)
        # Optional: Trim buffer if it gets too large independent of AI runs
        # while len(message_buffer) > MAX_BUFFER_SIZE * 2: # Example limit
        #     message_buffer.pop(0)
        print(f"Buffer size: {len(message_buffer)}/{MAX_BUFFER_SIZE} | Last msg in #{message.channel.name}: {now.isoformat()}")

    ctx = await bot.get_context(message)

    # --- Trigger AI Run ---
    # Trigger if buffer is full OR if the bot is mentioned (only in guilds for mention trigger)
    trigger_ai = (len(message_buffer) >= MAX_BUFFER_SIZE) or \
                 (bot.user.mentioned_in(message) and isinstance(message.channel, discord.TextChannel))

    if trigger_ai and len(message_buffer) > 0:
        print(f"Triggering AI run (Buffer size: {len(message_buffer)}, Mentioned: {bot.user.mentioned_in(message)})")
        run_command = bot.get_command("run_ai_chat")

        if run_command:
            buffer_copy = list(message_buffer)
            message_buffer.clear() # Clear global buffer
            await ctx.invoke(run_command, current_buffer=buffer_copy)
        else:
            print("Error: Could not find the run_ai_chat command.")
            await ctx.send("Internal Error: Could not trigger AI processing.")
            message_buffer.clear() # Still clear buffer

    # Process regular bot commands (like ~$hello)
    await bot.process_commands(message)


# --- Inactivity Check Task ---
@tasks.loop(minutes=1) # Check every 10 minutes
async def check_channel_activity():
    print("[Task Check Activity] Running check...")
    now = discord.utils.utcnow()
    for guild in bot.guilds:
        print(f"[Task Check Activity] Checking guild: {guild.name} ({guild.id})")
        if not guild.me: # Bot potentially kicked?
            print(f"[Task Check Activity] Bot not found in guild {guild.name}, skipping.")
            continue

        for channel in guild.text_channels:
             # Basic permission check first
            if not channel.permissions_for(guild.me).send_messages:
                # print(f"[Task Check Activity] Skipping #{channel.name}, no send perms.")
                continue
            if not channel.permissions_for(guild.me).view_channel:
                 # print(f"[Task Check Activity] Skipping #{channel.name}, no view perms.")
                 continue

            channel_id = channel.id
            last_msg_time = last_message_timestamps.get(channel_id)

            # If we have never seen a message, try to fetch the last one to initialize
            if last_msg_time is None:
                 try:
                     # Fetch last message to initialize timestamp if needed
                     async for last_msg in channel.history(limit=1):
                         if last_msg:
                             last_message_timestamps[channel_id] = last_msg.created_at
                             last_msg_time = last_msg.created_at
                             print(f"[Task Check Activity] Initialized last msg time for #{channel.name} to {last_msg_time.isoformat()}")
                         break # Only need the very last one
                     # If history is empty or inaccessible, record check time so we don't spam fetch
                     if last_msg_time is None:
                          last_message_timestamps[channel_id] = now
                          print(f"[Task Check Activity] Channel #{channel.name} appears empty or inaccessible, setting timestamp to now.")

                 except discord.Forbidden:
                     print(f"[Task Check Activity] Forbidden to read history in #{channel.name}, cannot check inactivity.")
                     # Mark as checked recently to avoid retrying constantly
                     last_message_timestamps[channel_id] = now
                     continue
                 except discord.HTTPException as e:
                     print(f"[Task Check Activity] HTTPException reading history in #{channel.name}: {e}")
                     # Mark as checked recently
                     last_message_timestamps[channel_id] = now
                     continue


            # Proceed if we have a timestamp
            if last_msg_time:
                time_since_last_msg = now - last_msg_time
                print(f"[Task Check Activity] Channel #{channel.name}: Last msg {time_since_last_msg} ago.")

                if time_since_last_msg > INACTIVITY_THRESHOLD:
                    # Check cooldown for conversation starters in this channel
                    last_starter_time = last_starter_sent.get(channel_id)
                    if last_starter_time and (now - last_starter_time < CONVERSATION_STARTER_COOLDOWN):
                        print(f"[Task Check Activity] Channel #{channel.name} inactive, but starter cooldown active.")
                        continue # Skip, still on cooldown

                    print(f"[Task Check Activity] Channel #{channel.name} inactive for {time_since_last_msg}. Triggering conversation starter.")
                    # --- Trigger AI for conversation starter ---
                    try:
                        # Fetch current presence data for context
                        online, idle, dnd, offline = 0, 0, 0, 0
                        if guild.member_count > 1000 and not bot.intents.members:
                             print("[WARN] Large server and missing Members Intent - presence data inaccurate.")
                        else:
                             # Ensure member list is available, might need fetch_members if cache is stale
                             # Check if chunking happened or fetch if needed
                             if guild.chunked == False and bot.intents.members:
                                 print(f"Guild {guild.name} not chunked, fetching members...")
                                 await guild.chunk() # Use fetch_members if chunk is deprecated/fails
                                 # async for member in guild.fetch_members(limit=None): pass # Alt fetch

                             for member in guild.members:
                                if not member.bot:
                                    if member.status == discord.Status.online: online += 1
                                    elif member.status == discord.Status.idle: idle += 1
                                    elif member.status == discord.Status.dnd: dnd += 1
                                    elif member.status == discord.Status.offline: offline += 1
                                    # Note: invisible treated as offline here

                        presence_summary = f"*   Online Users: {online}\n*   Idle/AFK Users: {idle}\n*   Do Not Disturb Users: {dnd}\n*   Offline Users: {offline}"

                        starter_prompt = f"""
You are an AI assistant in a Discord server named {guild.name}.
The channel #{channel.name} (ID: {channel_id}) has been inactive for over an hour.
Your goal is to generate a friendly and engaging conversation starter message appropriate for this channel.
Keep it relatively short and open-ended. Avoid anything controversial.
Consider the current server member status for tone (e.g., maybe less energetic if many are offline/DND, more engaging if many online).

**Current Server Status ({guild.name}):**
{presence_summary}

**CRITICAL:** Your response MUST be ONLY the `!say` command to send the message to the inactive channel.
Format: `!say(CHANNEL_ID, "Your conversation starter message here.")`
Example: `!say({channel_id}, "It's been quiet! What's everyone's favorite weekend activity?")`

Generate the `!say` command now.
"""
                        print(f"[Task Check Activity] Generating starter for #{channel.name} ({channel_id})...")
                        # print(f"Starter Prompt:\n{starter_prompt}") # Debugging

                        gemini_starter_messages = [
                            {"role": "user", "parts": [starter_prompt]},
                            # No priming needed here, the prompt is very specific
                        ]

                        # Use asyncio.to_thread for the blocking API call
                        response = await asyncio.to_thread(
                            gemini_model.generate_content,
                            contents=gemini_starter_messages,
                            # safety_settings=... # Add safety if needed
                        )

                        ai_response_text = ""
                        try:
                           ai_response_text = response.text
                           print(f"[Task Check Activity] Gemini Response for starter:\n{ai_response_text}")
                        except ValueError as e:
                           print(f"[Task Check Activity] Error getting text from Gemini starter response: {e}")
                           print(f"Prompt Feedback: {response.prompt_feedback}")
                           # Potentially log safety ratings if response blocked
                           continue # Skip this channel for now


                        # --- Find and Execute the !say Command ---
                        commands_to_execute = find_ai_commands(ai_response_text)
                        if commands_to_execute:
                            # We expect only one !say command here
                            command_ok = False
                            for cmd_string in commands_to_execute:
                                # Basic validation: Does the command target the correct channel?
                                say_match = re.match(r"!say\(\s*(\d+)\s*,", cmd_string)
                                if say_match and int(say_match.group(1)) == channel_id:
                                    await execute_ai_command(cmd_string, feedback_channel=None, executing_guild=guild) # No user context for feedback
                                    command_ok = True
                                    break # Execute only the first valid command
                                else:
                                    print(f"[Task Check Activity] AI generated !say command for wrong channel ({say_match.group(1) if say_match else 'N/A'}) or malformed. Expected {channel_id}. Command: {cmd_string}")

                            if command_ok:
                                # Update timestamps to prevent immediate re-trigger and mark cooldown
                                last_message_timestamps[channel_id] = now
                                last_starter_sent[channel_id] = now
                                print(f"[Task Check Activity] Conversation starter sent to #{channel.name}. Timestamps updated.")
                        else:
                            print(f"[Task Check Activity] AI did not generate a valid !say command for starter in #{channel.name}.")
                            # Optionally, could try sending a default message, but might be noisy.
                            # Record check time to prevent immediate retry on failed generation.
                            # last_message_timestamps[channel_id] = now # Careful: this resets inactivity timer


                    except Exception as e:
                        print(f"ERROR: An error occurred during conversation starter generation/execution for #{channel.name}: {e}")
                        import traceback
                        print(f"Full Traceback:\n{traceback.format_exc()}")
                        # Record check time even on error to avoid spamming failures
                        last_message_timestamps[channel_id] = now


@check_channel_activity.before_loop
async def before_check_activity():
    print("[Task Check Activity] Waiting for bot to be ready...")
    await bot.wait_until_ready()
    print("[Task Check Activity] Bot ready, starting loop.")


# --- Bot Commands ---
@bot.command()
async def hello(ctx):
    await ctx.send(f"Hello {ctx.author.mention}!")

@bot.command(name="run_ai_chat")
async def run_ai_chat(ctx, current_buffer: list):
    """Handles the interaction with the Gemini API and executes commands."""
    if not current_buffer:
        print("run_ai_chat called with empty buffer.")
        return

    # --- Get Presence Info (if in a guild) ---
    presence_summary = "N/A (Direct Message)"
    guild_name = "N/A (Direct Message)"
    if ctx.guild:
        guild = ctx.guild
        guild_name = guild.name
        # Ensure members are available (might need fetch if cache is incomplete)
        if not guild.chunked and bot.intents.members:
             print(f"Guild {guild.name} not chunked in run_ai_chat, fetching members...")
             # await guild.chunk() # Or fetch_members
             async for member in guild.fetch_members(limit=None): pass # Ensure cache fill
             print("Member fetch complete for run_ai_chat.")


        online, idle, dnd, offline = 0, 0, 0, 0
        # Recalculate counts each time; status can change quickly
        for member in guild.members:
             if not member.bot:
                 if member.status == discord.Status.online: online += 1
                 elif member.status == discord.Status.idle: idle += 1
                 elif member.status == discord.Status.dnd: dnd += 1
                 elif member.status == discord.Status.offline: offline += 1
        presence_summary = f"*   Online Users: {online}\n*   Idle/AFK Users: {idle}\n*   Do Not Disturb Users: {dnd}\n*   Offline Users: {offline}"

    # --- Construct the prompt for Gemini ---
    system_instruction = f"""
You are a helpful and conversational AI assistant integrated into a Discord chat named {bot.user.name}.
Your Discord User ID is {bot.user.id}.
When users want your attention, they might mention you like this: <@{bot.user.id}>.
You can mention users in your responses using their ID like this: <@USER_ID>.

**Current Server Context:**
*   Server Name: {guild_name}
*   Current User Statuses:
{presence_summary}
(Note: Statuses reflect the last check and might not be real-time)

**Your Goal:** Participate in the conversation naturally, answer questions, and be helpful based ONLY on the provided history and context.

**CRITICAL: Interaction Rules**
*   **ONLY use the `!say` command to send messages.** Do NOT output any conversational text outside of a `!say` command's message parameter if you intend to use the command.
*   If you want to send a message to a specific channel, you MUST use the `!say` command formatted EXACTLY as shown below within your response.
*   If your entire response is just executing an action via a command, ONLY output the command itself.
*   If you are just answering a question or making a comment *without* needing to send it to a specific channel via command, then respond with plain text (this text will be *suppressed* if *any* command is also present in your response).

**Available Commands:**

1.  `!say(channel_id, "message content")`
    *   Sends the specified "message content" (must be enclosed in double or single quotes, can be multi-line) to the Discord channel with the exact `channel_id` (must be a number).
    *   Example: `!say(1142351742143582258, "Hello everyone!")`
    *   Example: `!say(9876543210, "Hi <@1234567890>, how are you?")`

**Conversation History (most recent messages):**
The following messages form the current context. Respond based ONLY on this history. Remember the interaction rules and context.
"""

    gemini_messages = [
        {"role": "user", "parts": [system_instruction]},
        {"role": "model", "parts": ["Understood. I will analyze the conversation history and current server context. I will respond using plain text for conversation, or ONLY the `!say(channel_id, \"message content\")` command if I need to send a message to a specific channel."]}
    ]
    gemini_messages.extend(current_buffer)

    try:
        print(f"--- Sending to Gemini ({GEMINI_MODEL_NAME}) ---")
        # print(f"Messages: {gemini_messages}") # Debugging
        print("------------------------------------")

        response = await asyncio.to_thread(
             gemini_model.generate_content,
             contents=gemini_messages
        )

        ai_response_text = ""
        try:
            ai_response_text = response.text
        except ValueError:
            print("Warning: Could not extract text from Gemini response. It might have been blocked.")
            print(f"Prompt Feedback: {response.prompt_feedback}")
            if response.candidates:
                 print(f"Finish Reason: {response.candidates[0].finish_reason}")
                 print(f"Safety Ratings: {response.candidates[0].safety_ratings}")
            await ctx.send(f"Sorry {ctx.author.mention}, my response was blocked or something went wrong. (Reason: {response.prompt_feedback or 'Unknown'})")
            return

        print(f"--- Gemini Raw Response ---")
        print(ai_response_text)
        print("--------------------------")

        # --- Find Commands FIRST ---
        commands_to_execute = find_ai_commands(ai_response_text)

        # --- Decide whether to send raw text OR execute commands ---
        if commands_to_execute:
            print(f"Commands found in AI response. Executing them instead of sending raw text.")
            for cmd_string in commands_to_execute:
                # Pass ctx.channel as the feedback channel for user-invoked commands
                await execute_ai_command(cmd_string, feedback_channel=ctx.channel, executing_guild=ctx.guild)
        elif ai_response_text:
            print("No commands found in AI response. Sending raw text.")
            if len(ai_response_text) > 2000:
                await ctx.send(ai_response_text[:1997] + "...") # Truncate
            else:
                await ctx.send(ai_response_text)
        else:
            print("AI returned an empty response and no commands.")
            # await ctx.send("AI processed the input but had nothing to say or do.") # Optional


    except Exception as e:
        print(f"ERROR: An error occurred during Gemini API call or processing: {e}")
        import traceback
        print(f"Full Traceback:\n{traceback.format_exc()}")
        try:
            await ctx.send(f"Sorry {ctx.author.mention}, I encountered an error trying to process that: `{e}`")
        except discord.HTTPException as send_error:
             print(f"ERROR: Could not send error message to Discord: {send_error}")


# --- Run the Bot ---
if __name__ == "__main__":
    if not DISCORD_TOKEN:
        print("FATAL ERROR: DISCORD_TOKEN environment variable not set.")
    elif not GEMINI_API_KEY:
        print("FATAL ERROR: GEMINI_API_KEY environment variable not set.")
    else:
        try:
            print("Starting bot...")
            bot.run(DISCORD_TOKEN)
        except discord.PrivilegedIntentsRequired:
            print("FATAL ERROR: Privileged Intents (Presence, Server Members) are required but not enabled.")
            print("Go to your bot application page -> Bot -> Enable PRESENCE INTENT and SERVER MEMBERS INTENT.")
        except discord.LoginFailure:
            print("FATAL ERROR: Login failed. Check your DISCORD_TOKEN.")
        except Exception as e:
            print(f"FATAL ERROR: An unexpected error occurred on startup: {e}")
            import traceback
            print(f"Full Traceback:\n{traceback.format_exc()}")